using Microsoft.UI;
using System.Collections.Generic;
using Windows.UI;

namespace ChartBase.utils;

public static class ChartColors
{
    private static Color[] _allColors = new Color[] {
        //Colors.Black,   Colors.Red,                 Colors.Yellow,      Colors.Orange,    Colors.Green,         Colors.Blue,
        //Colors.Purple,  Colors.PaleVioletRed,       Colors.LightYellow, Colors.Pink,      Colors.LightGreen,    Colors.LightBlue,
        //Colors.Cyan,    Colors.MediumVioletRed,     Colors.DarkMagenta, Colors.DeepPink,  Colors.ForestGreen,   Colors.DarkBlue,   
        //Colors.Gray,     Colors.DarkGoldenrod,                                               Colors.SkyBlue,
        //Colors.White,

Colors.AliceBlue,
Colors.Crimson,
Colors.DarkOrange,
Colors.Pink,
Colors.LightGreen,
Colors.Yellow,
Colors.Blue,
Colors.White,
Colors.BlueViolet,
Colors.Chartreuse,
//Colors.DarkBlue,
//Colors.DarkGreen,
Colors.DeepPink,

//Colors.AntiqueWhite,
//Colors.Aqua,
Colors.ForestGreen,
Colors.Aquamarine,
//Colors.Azure,
//Colors.Beige,
Colors.Bisque,
Colors.BlanchedAlmond,
Colors.Gold,

Colors.Brown,
Colors.BurlyWood,
Colors.CadetBlue,

Colors.Chocolate,
Colors.Coral,
Colors.CornflowerBlue,
Colors.Cornsilk,
Colors.Cyan,

Colors.DarkCyan,
Colors.DarkGoldenrod,
Colors.DarkGray,

Colors.DarkKhaki,
Colors.DarkOliveGreen,

//Colors.DarkOrchid,
Colors.DarkRed,
Colors.DarkSalmon,
Colors.DarkSeaGreen,
Colors.DarkSlateBlue,
Colors.DarkSlateGray,
Colors.DarkTurquoise,
Colors.DarkViolet,

Colors.DeepSkyBlue,
Colors.DimGray,
Colors.DodgerBlue,
Colors.Firebrick,
Colors.FloralWhite,

Colors.Gainsboro,
Colors.GhostWhite,

Colors.Goldenrod,
Colors.Gray,
Colors.Green,
Colors.GreenYellow,
Colors.Honeydew,
Colors.HotPink,
Colors.IndianRed,
Colors.Indigo,
Colors.Ivory,
Colors.Khaki,
Colors.Lavender,
Colors.LavenderBlush,
Colors.LawnGreen,
Colors.LemonChiffon,
Colors.LightBlue,
Colors.LightCoral,
Colors.LightCyan,
Colors.LightGoldenrodYellow,
Colors.LightGreen,
Colors.LightGray,
Colors.LightPink,
Colors.LightSalmon,
Colors.LightSeaGreen,
Colors.LightSkyBlue,
Colors.LightSlateGray,
Colors.LightSteelBlue,
Colors.LightYellow,
Colors.Lime,
Colors.LimeGreen,
Colors.Linen,
Colors.Magenta,
Colors.Maroon,
Colors.MediumAquamarine,
Colors.MediumBlue,
Colors.MediumOrchid,
Colors.MediumPurple,
Colors.MediumSeaGreen,
Colors.MediumSlateBlue,
Colors.MediumSpringGreen,
Colors.MediumTurquoise,
Colors.MediumVioletRed,
Colors.MidnightBlue,
Colors.MintCream,
Colors.MistyRose,
Colors.Moccasin,
Colors.NavajoWhite,
Colors.Navy,
Colors.OldLace,
Colors.Olive,
Colors.OliveDrab,
Colors.Orange,
Colors.OrangeRed,
Colors.Orchid,
Colors.PaleGoldenrod,
Colors.PaleGreen,
Colors.PaleTurquoise,
Colors.PaleVioletRed,
Colors.PapayaWhip,
Colors.PeachPuff,
Colors.Peru,
//Colors.Pink,
Colors.Plum,
Colors.PowderBlue,
Colors.Purple,
//Colors.Red,
Colors.RosyBrown,
Colors.RoyalBlue,
Colors.SaddleBrown,
Colors.Salmon,
Colors.SandyBrown,
Colors.SeaGreen,
Colors.Sienna,
Colors.Silver,
Colors.SkyBlue,
Colors.SlateBlue,
Colors.SlateGray,
Colors.Snow,
Colors.SpringGreen,
Colors.SteelBlue,
Colors.Tan,
Colors.Teal,
Colors.Thistle,
Colors.Tomato,
Colors.Turquoise,
Colors.Violet,
Colors.Wheat,
//Colors.White,
Colors.WhiteSmoke,
//Colors.Yellow,
Colors.YellowGreen,
Colors.Black,
    };


    private static Color[] _allBackgroundColors = new Color[] {
        Colors.Black,   
        Colors.Red,   Colors.DarkRed, Colors.IndianRed, Colors.MediumVioletRed, Colors.OrangeRed, Colors.PaleVioletRed,
        Colors.Orange,    Colors.Green,         Colors.Blue,
        Colors.Purple,  Colors.PaleVioletRed,       Colors.Pink,      Colors.LightGreen,    Colors.LightBlue,
        Colors.Cyan,    Colors.MediumVioletRed,     Colors.DeepPink,  Colors.ForestGreen,   Colors.DarkBlue,
        Colors.Gray,     Colors.DarkGoldenrod,                                               Colors.SkyBlue,
        Colors.White };

    public static Color GetBackgroundColor(int index)
    {
        return _allBackgroundColors[index % _allBackgroundColors.Length];
    }

    public static Color GetColor(int index)
    {
        return _allColors[ index % _allColors.Length ];
    }
}

